name: CI
on: [push]

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:migrate

      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel

      - name: Run FactoryBot linting
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rake factory_bot:lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:migrate

      - name: Run tests
        env:
          PSN_BASIC_TOKEN: ${{ secrets.PSN_BASIC_TOKEN }}
          PSN_CLIENT_ID: ${{ secrets.PSN_CLIENT_ID }}
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
        run: bundle exec rspec
